### ISSUE TITLE
Please Host this Repo...

### ISSUE THREAD

**Issue by abhishekraoas** [Mohasin-Haque/mock-OTP#1]
Hey!!! You did not host this repo...Please Host this Repo and I want see the Output

**Comment by Mohasin-Haque** [comment]
@abhishekraoas  this was just for practice but I glad that you want to see.. Please also add styling to it if you can.. Thank you😊

**Comment by abhishekraoas** [comment]
Yes Bro...I will do some stylish and make atrractive
